### ISSUE TITLE
x

### ISSUE THREAD

**Issue by DanielGherjavca** [jianveronica/Simtpomus#1]
.

**Comment by jianveronica** [comment]
Dacă mult stimabila ar avea sâni, cu siguranță nu dvs ar trimite poze cu
ei))
sâm., 11 feb. 2023, 10:33 Daniel Gherjavca ***@***.***> a
scris:

**Comment by DanielGherjavca** [comment]
Acceptam poze si cu ``izium``

**Comment by jianveronica** [comment]
Și dumneaei acceptă poze cu iuzium)

sâm., 11 feb. 2023, 10:40 Daniel Gherjavca ***@***.***> a
scris:

**Comment by DanielGherjavca** [comment]
![image](https://user-images.githubusercontent.com/67125532/218251441-78acd22a-d918-4480-8609-d44431f0329e.png)
